// spotless:off
package com.team900.frc2026.auto;

import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If the 2 imports above cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories, and removes the need
 * for JSON parsing to load a trajectory's essential data. DO NOT MODIFY THIS FILE YOURSELF! It is
 * automatically generated by Choreo.
 */
public record ChoreoTraj(
        String name,
        OptionalInt segment,
        double totalTimeSecs,
        Pose2d initialPoseBlue,
        Pose2d endPoseBlue) {
    public static final ChoreoTraj OneSwipe =
            new ChoreoTraj(
                    "OneSwipe",
                    OptionalInt.empty(),
                    4.73742,
                    new Pose2d(3.60754, 0.58164, Rotation2d.fromRadians(0.0)),
                    new Pose2d(3.28976, 2.21561, Rotation2d.fromRadians(3.14159)));

    public static final ChoreoTraj OneSwipeCenter =
            new ChoreoTraj(
                    "OneSwipeCenter",
                    OptionalInt.empty(),
                    5.19808,
                    new Pose2d(3.6, 4.05, Rotation2d.fromRadians(0.0)),
                    new Pose2d(3.35902, 2.2805, Rotation2d.fromRadians(2.96527)));

    public static final ChoreoTraj TwoAndThreeSwipe =
            new ChoreoTraj(
                    "TwoAndThreeSwipe",
                    OptionalInt.empty(),
                    6.26534,
                    new Pose2d(3.28976, 2.21561, Rotation2d.fromRadians(3.14159)),
                    new Pose2d(3.27859, 2.21561, Rotation2d.fromRadians(3.14159)));

    public static final ChoreoTraj TwoAndThreeSwipeCenter =
            new ChoreoTraj(
                    "TwoAndThreeSwipeCenter",
                    OptionalInt.empty(),
                    4.71857,
                    new Pose2d(3.35902, 2.2805, Rotation2d.fromRadians(2.96527)),
                    new Pose2d(3.29342, 2.22884, Rotation2d.fromRadians(2.41994)));

    /**
     * A map between trajectory names and their corresponding data. This allows for trajectory data
     * to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES =
            Map.ofEntries(
                    Map.entry("OneSwipe", OneSwipe),
                    Map.entry("OneSwipeCenter", OneSwipeCenter),
                    Map.entry("TwoAndThreeSwipe", TwoAndThreeSwipe),
                    Map.entry("TwoAndThreeSwipeCenter", TwoAndThreeSwipeCenter));

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj. WARNING: will raise an
     * exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException(
                    "Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }

    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger
     * trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
// spotless:on
